name: wortmeister
description: "A new Flutter project."
publish_to: 'none'
isar_version: &isar_version 3.1.8

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  another_flutter_splash_screen: ^1.2.1
  card_swiper: ^3.0.1
  cloud_firestore: ^5.6.3
  device_preview: ^1.2.0
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  firebase_messaging: ^15.2.2
  firebase_remote_config: ^5.4.0
  firebase_storage: ^12.4.3
  flip_card: ^0.7.0
  flutter_facebook_auth: ^7.1.1
  flutter_tts: ^4.2.2
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0  
  isar: 
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs: # contains Isar Core
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  openai_dart: ^0.4.5
  path_provider: ^2.1.5
  provider: ^6.1.2
  sentry_flutter: ^8.13.1
  shared_preferences: ^2.5.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  isar_generator: 
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icon.png"
    background_color: "#F4C7FF"
    theme_color: "#F4C7FF"
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/icon.png"