name: wortmeister
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.3
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  firebase_messaging: ^15.2.2
  firebase_remote_config: ^5.4.0
  flip_card: ^0.7.0
  flutter_tts: ^4.2.2
  get_it: ^8.0.3
  google_sign_in: ^6.2.2
  openai_dart: ^0.4.5
  provider: ^6.1.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/