// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5A1z-OonNZZtUi76ObSFh3yAuntrl6UY',
    appId: '1:78963345560:web:41fa0fdb2c780ce21668ed',
    messagingSenderId: '78963345560',
    projectId: 'wort-meister',
    authDomain: 'wort-meister.firebaseapp.com',
    storageBucket: 'wort-meister.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlYcM45SEyMuNCa7HC6_3WSuq4Fk7_wSY',
    appId: '1:78963345560:android:51c282c85f70ee081668ed',
    messagingSenderId: '78963345560',
    projectId: 'wort-meister',
    storageBucket: 'wort-meister.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAevYl21AkplPVbng4p9zoTeEVr4w0w9Xg',
    appId: '1:78963345560:ios:b28c08c1b9145ec51668ed',
    messagingSenderId: '78963345560',
    projectId: 'wort-meister',
    storageBucket: 'wort-meister.firebasestorage.app',
    iosClientId: '78963345560-unrb4c00cu73kj2jgs4ehvrlti79g6oi.apps.googleusercontent.com',
    iosBundleId: 'dev.nikkothe.wordmaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAevYl21AkplPVbng4p9zoTeEVr4w0w9Xg',
    appId: '1:78963345560:ios:b28c08c1b9145ec51668ed',
    messagingSenderId: '78963345560',
    projectId: 'wort-meister',
    storageBucket: 'wort-meister.firebasestorage.app',
    iosClientId: '78963345560-unrb4c00cu73kj2jgs4ehvrlti79g6oi.apps.googleusercontent.com',
    iosBundleId: 'dev.nikkothe.wordmaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5A1z-OonNZZtUi76ObSFh3yAuntrl6UY',
    appId: '1:78963345560:web:a4b5b157232529531668ed',
    messagingSenderId: '78963345560',
    projectId: 'wort-meister',
    authDomain: 'wort-meister.firebaseapp.com',
    storageBucket: 'wort-meister.firebasestorage.app',
  );

}